import { Octokit } from "@octokit/rest";
import { VerifiedPatch, PullRequestRecord, UsageSite, ClassifiedChange } from "@vigil/schemas";
import crypto from "crypto";
import { logger } from "@vigil/logger";
import { execa } from "execa";
import fs from "fs/promises";
import os from "os";
import path from "path";

const getOctokit = () => {
  // In a real environment, this would authenticate as a GitHub App installation
  // using @octokit/auth-app with an installation ID.
  // For MVP/testing, we use a personal access token if provided, or mock it.
  if (process.env.VIGIL_GITHUB_TOKEN && process.env.NODE_ENV !== "test") {
    return new Octokit({ auth: process.env.VIGIL_GITHUB_TOKEN });
  }
  return null;
};

export async function createDraftPullRequest(
  patch: VerifiedPatch,
  usageSite: UsageSite & { change: ClassifiedChange },
  owner: string,
  repo: string
): Promise<PullRequestRecord> {
  const octokit = getOctokit();
  
  if (!octokit) {
    logger.info("No GitHub token or in test mode. Returning mock PR record.");
    return {
      id: crypto.randomUUID(),
      installationId: crypto.randomUUID(), // Mock installation ID
      verifiedPatchId: patch.id,
      githubPrUrl: `https://github.com/${owner}/${repo}/pull/mock`,
      status: "open",
      openedAt: new Date().toISOString()
    };
  }

  // 1. Get default branch ref
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  });
  
  // 2. Create a new branch for the PR
  const branchName = `vigil-fix-${patch.id.substring(0, 8)}`;
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: refData.object.sha,
  });

  // 3. Apply the patch.diff and push
  if (process.env.VIGIL_GITHUB_TOKEN && process.env.NODE_ENV !== "test") {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "vigil-patch-"));
    try {
      const repoUrl = `https://x-access-token:${process.env.VIGIL_GITHUB_TOKEN}@github.com/${owner}/${repo}.git`;
      await execa("git", ["clone", repoUrl, tempDir]);
      await execa("git", ["fetch", "origin", branchName], { cwd: tempDir });
      await execa("git", ["checkout", branchName], { cwd: tempDir });
      
      const patchPath = path.join(tempDir, "changes.patch");
      await fs.writeFile(patchPath, patch.diff);
      
      // Use git apply to apply the unified diff
      await execa("git", ["apply", "changes.patch"], { cwd: tempDir });
      await fs.rm(patchPath); // cleanup
      
      await execa("git", ["config", "user.name", "Vigil Bot"], { cwd: tempDir });
      await execa("git", ["config", "user.email", "bot@vigil.example"], { cwd: tempDir });
      
      await execa("git", ["add", "."], { cwd: tempDir });
      await execa("git", ["commit", "-m", "Apply Vigil candidate patch"], { cwd: tempDir });
      await execa("git", ["push", "origin", branchName], { cwd: tempDir });
    } catch (err: any) {
      logger.error({ err, owner, repo }, "Failed to apply patch locally and push");
      throw err;
    } finally {
      await fs.rm(tempDir, { recursive: true, force: true });
    }
  }
  
  const title = `Vigil: ${usageSite.change.classification} change detected in ${usageSite.change.vendorId} contract`;
  
  // As per AGENTS.md §6.6 Canonical PR body template:
  const changeTitle = usageSite.change.classification === "breaking" ? "⚠️ Breaking change detected" : "ℹ️ Contract update detected";
  
  let verificationText = "";
  if (!patch.testSuiteDetected) {
    verificationText = `⚠️ unverified — no test suite detected`;
  } else if (patch.testsPassed) {
    verificationText = `✅ Sandboxed test run passed — full log: [link](${patch.logRef})
Container: isolated, no network egress, ephemeral, deleted after this run.`;
  } else {
    verificationText = `❌ Sandboxed test run failed — full log: [link](${patch.logRef})`;
  }

  const body = `## ${changeTitle}: ${usageSite.change.vendorId} — \`${usageSite.change.path}\`

**What changed:** ${usageSite.change.rationale}
**Classification:** \`${usageSite.change.classification}\` (confidence: ${(usageSite.change.confidence * 100).toFixed(0)}%, rule: \`${usageSite.change.ruleTriggered || 'llm_fallback'}\`)
**Source:** ${usageSite.change.vendorId} contract → [view diff](https://dashboard.vigil.example/changes/${usageSite.change.id})
**Affected call site:** \`${usageSite.filePath}:${usageSite.startLine}-${usageSite.endLine}\`

### What this PR does
Vigil has generated a candidate patch to address this contract update.
(Generated by \`${patch.generatorModel}\` with confidence ${(patch.generatorConfidence * 100).toFixed(0)}%)

### Verification
${verificationText}

### To revert
This is a single, self-contained commit. \`git revert <sha>\` cleanly undoes it.

---
*Opened by Vigil on behalf of your ${usageSite.change.vendorId} tracking configuration. Never
auto-merged. [Adjust what Vigil opens PRs for →](https://dashboard.vigil.example/installations/${usageSite.installationId})*`;

  const { data: prData } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branchName,
    base: defaultBranch,
    draft: true, // CRITICAL: Must be a draft
  });
  
  return {
    id: crypto.randomUUID(),
    installationId: "installation-id",
    verifiedPatchId: patch.id,
    githubPrUrl: prData.html_url,
    status: "open",
    openedAt: new Date().toISOString()
  };
}
